name: Check format and test build
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run tests
        run: |
          pnpm run lint:check
          pnpm run prettier:check
          pnpm run check
          pnpm run build
