name: Capture Screenshot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v0
      - name: Capture Webpage Screenshot
        uses: saadmk11/comment-website-screenshot@v0.5
        with:
          upload_to: github_branch
          capture_changed_html_files: yes
          capture_html_file_paths: "dist/index.html"
